version: '3'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: ["python", "app/server.py", "--n", "49"]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    command: ["python", "app/client.py"]
